'use strict';

angular.module('pdAssets', [
    'pdActivityCard',
    'pdAssetsTemplates',
    'pdCalExport',
    'pdCheckboxesToList',
    'pdColorPicker',
    'pdConfirm',
    'pdDrawerNav',
    'pdFacebook',
    'pdFontUpload',
    'pdForm',
    'pdHeaderNav',
    'pdImageCrop',
    'pdInsuranceWidgets',
    'pdLoader',
    'pdLoading',
    'pdOverlay',
    'pdPagination',
    'pdPokit',
    'pdResourceGrid',
    'pdScrolling',
    'pdSelect',
    'pdSpinner',
    'pdTiles',
    'pdToast',
    'pdUtils',
    'pdValues',
    'pdWorkflow'
]);
